### ISSUE TITLE
bsv.util.js does not have integerAsBuffer

### ISSUE THREAD

**Issue by monkeylord** [deanmlittle/bsv-p2p#7]
TypeError: JSUtil.integerAsBuffer is not a function
    at addNetwork (.\node_modules\bsv-p2p\lib\networks.js:105:28)
    at Object.<anonymous> (.\node_modules\bsv-p2p\lib\networks.js:243:1)

**Comment by monkeylord** [comment]
bsv library removed this in commit https://github.com/moneybutton/bsv/commit/9dd354451da79d7d8a411a329ec2e1afe4c3b04c

It's replaced by `Buffer.prototype.writeUInt32BE`

**Comment by monkeylord** [comment]
This is available in bsv@1.1.0
