### ISSUE TITLE
Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by corper** [deanmlittle/bsv-p2p#8]
I got this error when I install this package and run my program:

```
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/some_dir/node_modules/bsv-p2p/lib/networks.js:1:71)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

Should lodash be added to package.json?

**Comment by deanmlittle** [comment]
Seems so. Will investigate. Thanks!
